job:
  name: moex_futures_job
  version_label: 1.0

pod:
  name: moex_futures_pod
  version_label: 1.0

image:
  repository: moex_futures_positions
  tag: "v1"
  pullPolicy: Never
  restartPolicy: Never

## Values in here get injected as environment variables
## Needed chart reinstall for apply changes
env:
  # Futures contract name. Example: CNY, RTS etc.
  contract: ""

  # Requesting date
  day: 0
  month: 0
  year: 0

  # Period of days from requesting date (can be negative or zero).
  # Negative value is a past days, zero value is only requesting date, positive value is a future days.
  range: 0

  # Connection settings to PostgreSQL server
  pg_host: ""
  pg_port: 5432
  pg_user: ""
  pg_password: ""
  pg_db: ""
