apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.job.name }}
spec:
  template:
    metadata:
      name: {{ .Values.pod.name }}
      labels:
        app.kubernetes.io/name: {{ .Values.pod.name }}
    spec:
      restartPolicy: {{ .Values.image.restartPolicy }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONTRACT
              value: {{ .Values.env.contract }}
            - name: DAY
              value: {{ .Values.env.day | quote }}
            - name: MONTH
              value: {{ .Values.env.month | quote }}
            - name: YEAR
              value: {{ .Values.env.year | quote }}
            - name: RANGE
              value: {{ .Values.env.range | quote }}
            - name: PG_HOST
              value: {{ .Values.env.pg_host }}
            - name: PG_PORT
              value: {{ .Values.env.pg_port | quote }}
            - name: PG_USER
              value: {{ .Values.env.pg_user }}
            - name: PG_PASSWORD
              value: {{ .Values.env.pg_password }}
            - name: PG_DB
              value: {{ .Values.env.pg_db }}